name: Publish Documentation
  
on:
  workflow_dispatch:

  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build documentation
        run:  |
          docker run --rm -v $(pwd):/work pspiagicw/doc-generator

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build



